version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: helpdesk-backend-prod
    ports:
      - "8000:8000"
    environment:
      # Environment configuration
      - ENVIRONMENT=production
      # Database configuration (will be set via .env file)
      - DB_TYPE=mariadb
      - DB_HOST=${RDS_ENDPOINT}
      - DB_PORT=3306
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${RDS_DATABASE}
      # AWS Secrets Manager
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /var/log/helpdesk:/app/logs
    networks:
      - helpdesk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ../vue-app
      dockerfile: Dockerfile
    container_name: helpdesk-frontend-prod
    ports:
      - "80:3000"
      - "443:3001"  # For SSL
    environment:
      - VITE_API_BASE_URL=https://${DOMAIN_NAME}/api
    networks:
      - helpdesk-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: helpdesk-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - /var/log/nginx:/var/log/nginx
    networks:
      - helpdesk-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  helpdesk-network:
    driver: bridge
